//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.09 at 05:24:34 PM CEST
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.openarchives.org/OAI/2.0/oai_dc/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, xmlns = {
    @XmlNs(prefix = "oai_dc", namespaceURI = "http://www.openarchives.org/OAI/2.0/oai_dc/"),
    @XmlNs(prefix = "dc", namespaceURI = "http://purl.org/dc/elements/1.1/")
})
package nl.waisda.oaipmh.model.jaxb.dc;

import javax.xml.bind.annotation.XmlNs;